services:
  postgres:
    image: postgres:17
    container_name: lacksfer-postgres
    environment:
      POSTGRES_DB: lacksfer
      POSTGRES_USER: lack
      POSTGRES_PASSWORD: kcal
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: lacksfer-azurite
    command: azurite --blobHost 0.0.0.0 --location /data --skipApiVersionCheck
    ports:
      - "10000:10000"
    volumes:
      - azurite-data:/data

volumes:
  postgres-data:
  azurite-data: