%dev.quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/lacksfer
%dev.quarkus.datasource.username=lack
%dev.quarkus.datasource.password=kcal

%dev.quarkus.flyway.migrate-at-start=true
%dev.quarkus.hibernate-orm.schema-management.strategy=validate
%dev.quarkus.hibernate-orm.log.sql=true

%dev.lacksfer.upload.max-size-bytes=104857600

%dev.azurite.connection-string=UseDevelopmentStorage=true
%dev.azurite.container-name=files


## TEST
%test.azurite.connection-string=UseDevelopmentStorage=true
%test.azurite.container-name=files
%test.lacksfer.upload.max-size-bytes=104857600 

%test.quarkus.datasource.db-kind=postgresql
%test.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/lacksfer
%test.quarkus.datasource.username=lack
%test.quarkus.datasource.password=kcal
%test.quarkus.flyway.migrate-at-start=true
%test.quarkus.hibernate-orm.schema-management.strategy=validate