%dev.quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/lacksfer
%dev.quarkus.datasource.username=lack
%dev.quarkus.datasource.password=kcal

%dev.quarkus.hibernate-orm.schema-management.strategy=update
%dev.quarkus.hibernate-orm.log.sql=true