%dev.quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/lacksfer
%dev.quarkus.datasource.username=lack
%dev.quarkus.datasource.password=kcal

%dev.quarkus.hibernate-orm.schema-management.strategy=update
%dev.quarkus.hibernate-orm.log.sql=true

%dev.azurite.connection-string=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50zQ==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;
%dev.azurite.container-name=files